build-docker-image:
  stage: build
  script:
    - docker build --tag volumio-mqtt-docker:latest --tag volumio-mqtt-docker:v1.0.0 .

deploy-rpi:
  stage: deploy
  script:
    - docker stop volumio_mqtt || true && docker rm volumio_mqtt || true
    - >
      docker run -d --network host --name volumio_mqtt --restart unless-stopped
      --env IS_DEBUG=$CI_DEBUG
      --env VOLUMIO_HOST=$CI_VOLUMIO_HOST
      --env MQTT_HOST=$CI_MQTT_HOST
      --env MQTT_USERNAME=$CI_MQTT_USERNAME
      --env MQTT_PASSWORD=$CI_MQTT_MQTT_PASSWORD
      --env MQTT_DEVICE=$CI_DEVICE volumio-mqtt-docker

remove-untagged-images:
  stage: .post
  script:
    - docker image prune --filter="dangling=true" --force
