build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - hostname -I
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - pwd
    - docker build --tag volumio-mqtt-docker .
    - docker tag volumio-mqtt-docker:latest volumio-mqtt-docker:v1.0.0
    - docker run -d --network host --name volumio_mqtt --restart unless-stopped volumio-mqtt-docker -e DEBUG=$CI_DEBUG -e VOLUMIO_HOST=$CI_VOLUMIO_HOST -e MQTT_HOST=$CI_MQTT_HOST -e DEVICE=CI_DEVICE
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."